"""initial

Revision ID: fd301443d352
Revises: 
Create Date: 2026-02-21 15:15:21.874923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd301443d352'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('net_liquidation', sa.Float(), nullable=True),
    sa.Column('total_cash', sa.Float(), nullable=True),
    sa.Column('buying_power', sa.Float(), nullable=True),
    sa.Column('day_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account')
    )
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('fcf_yield', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roic', sa.Float(), nullable=True),
    sa.Column('debt_equity', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('fcf_margin', sa.Float(), nullable=True),
    sa.Column('revenue_cagr_3y', sa.Float(), nullable=True),
    sa.Column('eps_cagr_3y', sa.Float(), nullable=True),
    sa.Column('revenue_cagr_5y', sa.Float(), nullable=True),
    sa.Column('eps_growth_5y', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('payout_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_cagr_5y', sa.Float(), nullable=True),
    sa.Column('consecutive_div_growth_years', sa.Integer(), nullable=True),
    sa.Column('earnings_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('sector_pe_median', sa.Float(), nullable=True),
    sa.Column('sector_ev_ebitda_median', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl_pct', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'account')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('suggested_size_pct', sa.Float(), nullable=True),
    sa.Column('suggested_tranche', sa.Integer(), nullable=True),
    sa.Column('total_tranches', sa.Integer(), nullable=True),
    sa.Column('timing_note', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('conflicting_signals', sa.Text(), nullable=True),
    sa.Column('supporting_strategies', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('briefing_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'briefing_type')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('signal', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('key_metrics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='ck_signal_confidence'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('settle_date', sa.Date(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ibkr_trade_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ibkr_trade_id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_horizon', sa.String(), nullable=False),
    sa.Column('risk_tolerance', sa.String(), nullable=False),
    sa.Column('max_single_position_pct', sa.Float(), nullable=False),
    sa.Column('max_sector_pct', sa.Float(), nullable=False),
    sa.Column('preferred_strategies', sa.Text(), nullable=False),
    sa.Column('hybrid_profiles', sa.Text(), nullable=False),
    sa.Column('tax_sensitive', sa.Boolean(), nullable=False),
    sa.Column('min_confidence_to_act', sa.Integer(), nullable=False),
    sa.Column('scale_in_enabled', sa.Boolean(), nullable=False),
    sa.Column('scale_in_tranches', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('alert_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('user_preferences')
    op.drop_table('transactions')
    op.drop_table('sync_log')
    op.drop_table('signals')
    op.drop_table('research_cache')
    op.drop_table('recommendations')
    op.drop_table('positions')
    op.drop_table('market_data')
    op.drop_table('fundamentals')
    op.drop_table('account_summary')
    # ### end Alembic commands ###
